// DESCRIPTION: Verilator: Verilog Test module
//
// This file ONLY is placed under the Creative Commons Public Domain, for
// any use, without warranty, 2025 by Geza Lore.
// SPDX-License-Identifier: CC0-1.0

`define signal(name, expr) wire [$bits(expr)-1:0] ``name = expr

module t (
`include "portlist.vh" // Boilerplate generated by t_dfg_break_cycles.py
  rand_a, rand_b, srand_a, srand_b
);

`include "portdecl.vh" // Boilerplate generated by t_dfg_break_cycles.py

  input rand_a;
  input rand_b;
  input srand_a;
  input srand_b;
  wire logic        [63:0] rand_a;
  wire logic        [63:0] rand_b;
  wire logic signed [63:0] srand_a;
  wire logic signed [63:0] srand_b;

  //////////////////////////////////////////////////////////////////////////

  //logic [2:0] simple;
  //always_comb begin
  //  simple[0] = rand_a[0];
  //  simple[1] = rand_a[1];
  //  simple[2] = rand_a[2];
  //end
  //`signal(SIMPLE, simple);

  //logic [2:0] self_circular;
  //always_comb begin
  //  self_circular[0] = rand_a[0];
  //  self_circular[1] = ~self_circular[0];
  //  self_circular[2] = ~self_circular[1];
  //end
  //`signal(SELF_CIRCULAR, self_circular);

  //logic [3:0] split_circular;
  //always_comb begin
  //  split_circular[0] = rand_a[0];
  //  split_circular[2] = rand_a[1];
  //end
  //always_comb begin
  //  split_circular[1] = ~split_circular[0];
  //  split_circular[3] = ~split_circular[2];
  //end
  //`signal(SPLIT_CIRCULAR, split_circular);

  logic [3:0] conditional_a;
  always_comb begin
    conditional_a = 4'd0;
    if (rand_a[0]) begin
      conditional_a = rand_b[3:0];
    end else begin
      conditional_a = ~rand_b[3:0];
    end
  end
  `signal(CONDITONAL_A, conditional_a);

  //logic [3:0] conditional_b;
  //always_comb begin
  //  conditional_b = 4'd0;
  //  if (rand_a[0]) begin
  //    conditional_b = rand_b[3:0];
  //  end
  //end
  //`signal(CONDITONAL_B, conditional_b);

  //logic [3:0] conditional_c;
  //always_comb begin
  //  if (rand_a[0]) begin
  //    conditional_c = rand_b[3:0];
  //  end else if (rand_a[1]) begin
  //    conditional_c = ~rand_b[3:0];
  //  end else begin
  //    conditional_c = rand_b[7:4];
  //  end
  //end
  //`signal(CONDITONAL_C, conditional_c);

  //logic [3:0] conditional_d;
  //always_comb begin
  //  conditional_d = 4'd0;
  //  if (rand_a[0]) begin
  //    conditional_d = rand_b[3:0];
  //  end else begin
  //    if (rand_a[1]) begin
  //      conditional_d = rand_b[3:0];
  //    end else begin
  //      conditional_d = rand_b[7:4];
  //    end
  //    conditional_d = ~conditional_d;
  //  end
  //end
  //`signal(CONDITONAL_D, conditional_d);

endmodule


