// DESCRIPTION: Verilator: Verilog Test module
//
// This file ONLY is placed under the Creative Commons Public Domain, for
// any use, without warranty, 2025 by Geza Lore.
// SPDX-License-Identifier: CC0-1.0

`define signal(name, expr) wire [$bits(expr)-1:0] ``name = expr

module t (
`include "portlist.vh" // Boilerplate generated by t_dfg_break_cycles.py
  rand_a, rand_b, srand_a, srand_b
);

`include "portdecl.vh" // Boilerplate generated by t_dfg_break_cycles.py

  input rand_a;
  input rand_b;
  input srand_a;
  input srand_b;
  wire logic        [63:0] rand_a;
  wire logic        [63:0] rand_b;
  wire logic signed [63:0] srand_a;
  wire logic signed [63:0] srand_b;

  //////////////////////////////////////////////////////////////////////////

  //logic [2:0] simple;
  //always_comb begin
  //  simple[0] = rand_a[0];
  //  simple[1] = rand_a[1];
  //  simple[2] = rand_a[2];
  //end
  //`signal(SIMPLE, simple);

  //logic [2:0] circular;
  //always_comb begin
  //  circular[0] = rand_a[0];
  //  circular[1] = ~circular[0];
  //  circular[2] = ~circular[1];
  //end
  //`signal(CIRCULAR, circular);

  logic [4:0] a;
  always_comb begin
    a[0] = rand_a[0];
    a[2] = rand_a[1];
  end
  always_comb begin
    a[1] = ~a[0];
    a[3] = ~a[2];
  end
  `signal(FOO, a);

endmodule
