// -*- mode: C++; c-file-style: "cc-mode" -*-
//=============================================================================
//
// Code available from: https://verilator.org
//
// This program is free software; you can redistribute it and/or modify it
// under the terms of either the GNU Lesser General Public License Version 3
// or the Perl Artistic License Version 2.0.
// SPDX-FileCopyrightText: 2001-2026 Wilson Snyder
// SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0
//
//=============================================================================
///
/// \file
/// \brief Verilated C++ tracing in FST format implementation code
///
/// This file must be compiled and linked against all Verilated objects
/// that use --trace-fst.
///
/// Use "verilator --trace-fst" to add this to the Makefile for the linker.
///
//=============================================================================

// clang-format off

#include "verilated.h"
#include "verilated_fst_c.h"

// Include fstcpp cpp file directly
#include "fstcpp/fstcpp_variable_info.cpp"
#include "fstcpp/fstcpp_writer.cpp"

#include <algorithm>
#include <cstdint>
#include <iterator>
#include <type_traits>
#include <vector>

#if defined(_WIN32) && !defined(__MINGW32__) && !defined(__CYGWIN__)
# include <io.h>
#else
# include <unistd.h>
#endif

// clang-format on

//=============================================================================
// Check that forward declared types matches the FST API types

static_assert(std::is_same<vlFstHandle, fst::Handle>::value, "vlFstHandle mismatch");
static_assert(std::is_same<vlFstEnumHandle, fst::EnumHandle>::value, "vlFstHandle mismatch");

//=============================================================================
// Specialization of the generics for this trace format

#define VL_SUB_T VerilatedFst
#define VL_BUF_T VerilatedFstBuffer
#include "verilated_trace_imp.h"
#undef VL_SUB_T
#undef VL_BUF_T

//=============================================================================
// VerilatedFst

VerilatedFst::VerilatedFst(void* /*fst*/) {}

VerilatedFst::~VerilatedFst() {
    if (m_fst) VL_DO_CLEAR(delete m_fst, m_fst = nullptr);  // LCOV_EXCL_BR_LINE
}

void VerilatedFst::open(const char* filename) VL_MT_SAFE_EXCLUDES(m_mutex) {
    const VerilatedLockGuard lock{m_mutex};
    m_fst = new fst::Writer{filename};  // LCOV_EXCL_BR_LINE
    m_fst->setWriterPackType(fst::WriterPackType::LZ4);
    m_fst->setTimecale(int8_t(round(log10(timeRes()))));
    // if (m_useFstWriterThread) fstWriterSetParallelMode(m_fst, 1);
    m_fst->setWriter("Generated by VerilatedFst");
    fullDump(true);  // First dump must be full for fst

    // The variables of this file are created when the signals are declared
    m_code2symbol.clear();
    Super::traceInit();
}

void VerilatedFst::close() VL_MT_SAFE_EXCLUDES(m_mutex) {
    const VerilatedLockGuard lock{m_mutex};
    emitTimeChangeMaybe();
    if (m_fst) {
        m_fst->close();
        VL_DO_CLEAR(delete m_fst, m_fst = nullptr);
    }
}

void VerilatedFst::flush() VL_MT_SAFE_EXCLUDES(m_mutex) {
    const VerilatedLockGuard lock{m_mutex};
    emitTimeChangeMaybe();
    if (m_fst) m_fst->flushValueChangeData();  // LCOV_EXCL_BR_LINE
}

void VerilatedFst::emitTimeChange(uint64_t timeui) {
    if (!timeui) m_fst->emitTimeChange(timeui);
    m_timeui = timeui;
}

VL_ATTR_ALWINLINE
void VerilatedFst::emitTimeChangeMaybe() {
    if (VL_UNLIKELY(m_timeui)) {
        m_fst->emitTimeChange(m_timeui);
        m_timeui = 0;
    }
}

//=============================================================================
// Decl

void VerilatedFst::declareEnum(const VlRtmdDataType& dtype) {
    std::vector<std::pair<const char*, const char*>> items;
    items.reserve(dtype.enumItemCount());
    for (uint32_t i = 0; i < dtype.enumItemCount(); ++i) {
        const VlRtmdDataTypeRow::EnumItem& item = dtype.enumItem(i);
        items.emplace_back(item.m_namep, item.m_valuep);
    }
    const fst::EnumHandle enumNum = m_fst->createEnumTable(dtype.enumName(), dtype.width(), items);
    m_local2fstdtype.emplace(dtype, enumNum).second;
}

// Open a scope of the given type
static void vlFstBeginScope(fst::Writer* fstp, fst::Hierarchy::ScopeType type, const char* namep) {
    fstp->setScope(type, std::string{namep}, std::string{});
}

// Open a scope of the given type, after an attribute holding 'value'
static void vlFstBeginScope(fst::Writer* fstp, fst::Hierarchy::ScopeType type, const char* namep,
                            fst::Hierarchy::AttrType attrType,
                            fst::Hierarchy::AttrSubType attrSubType, const char* attrNamep,
                            uint64_t value) {
    fstp->setAttrBegin(attrType, attrSubType, attrNamep, value);
    vlFstBeginScope(fstp, type, namep);
}

void VerilatedFst::endScope() { m_fst->upscope(); }

// The bounds attribute of an array
static uint64_t vlFstBounds(int left, int right) {
    return static_cast<uint64_t>(static_cast<uint32_t>(left)) << 32
           | static_cast<uint64_t>(static_cast<uint32_t>(right));
}

void VerilatedFst::openRoot(const char* namep) {
    vlFstBeginScope(m_fst, fst::Hierarchy::ScopeType::VCD_MODULE, namep);
}

void VerilatedFst::openInstance(InstanceKind kind, const char* namep, const char*) {
    vlFstBeginScope(m_fst,
                    kind == InstanceKind::INTERFACE ? fst::Hierarchy::ScopeType::VCD_INTERFACE
                                                    : fst::Hierarchy::ScopeType::VCD_MODULE,
                    namep);
}

void VerilatedFst::openIfaceRef(const char* namep, const char*) {
    vlFstBeginScope(m_fst, fst::Hierarchy::ScopeType::VCD_INTERFACE, namep);
}

void VerilatedFst::openScope(ScopeKind, const char* namep) {
    vlFstBeginScope(m_fst, fst::Hierarchy::ScopeType::VCD_MODULE, namep);
}

void VerilatedFst::openUnpackedArray(const char* namep, int left, int right) {
    vlFstBeginScope(m_fst, fst::Hierarchy::ScopeType::SV_ARRAY, namep,
                    fst::Hierarchy::AttrType::ARRAY, fst::Hierarchy::AttrSubType::ARRAY_UNPACKED,
                    "bounds", vlFstBounds(left, right));
}

void VerilatedFst::openUnpackedStruct(const char* namep, uint32_t memberCount) {
    vlFstBeginScope(m_fst, fst::Hierarchy::ScopeType::VCD_STRUCT, namep,
                    fst::Hierarchy::AttrType::PACK, fst::Hierarchy::AttrSubType::PACK_UNPACKED,
                    "members", memberCount);
}

void VerilatedFst::openPackedArray(const char* namep, int left, int right) {
    vlFstBeginScope(m_fst, fst::Hierarchy::ScopeType::SV_ARRAY, namep,
                    fst::Hierarchy::AttrType::ARRAY, fst::Hierarchy::AttrSubType::ARRAY_PACKED,
                    "bounds", vlFstBounds(left, right));
}

void VerilatedFst::openPackedStruct(const char* namep, uint32_t memberCount) {
    vlFstBeginScope(m_fst, fst::Hierarchy::ScopeType::VCD_STRUCT, namep,
                    fst::Hierarchy::AttrType::PACK, fst::Hierarchy::AttrSubType::PACK_PACKED,
                    "members", memberCount);
}

void VerilatedFst::openPackedUnion(const char* namep, uint32_t memberCount) {
    vlFstBeginScope(m_fst, fst::Hierarchy::ScopeType::VCD_UNION, namep,
                    fst::Hierarchy::AttrType::PACK, fst::Hierarchy::AttrSubType::PACK_PACKED,
                    "members", memberCount);
}

// The builtin type of a value: that of the base of an enum, or of the elements of a packed array.
// Packed structs and unions, traced whole without --trace-structs, are 'logic'.
static VlRtmdDataType::AtomKind vlFstAtomKind(const VlRtmdDataType& dtype) {
    if (dtype.isAtom()) return dtype.atomKind();
    if (dtype.isEnum()) return vlFstAtomKind(dtype.enumBase());
    if (dtype.isPackedArray()) return vlFstAtomKind(dtype.elemType());
    return VlRtmdDataType::AtomKind::LOGIC;
}

void VerilatedFst::declareSignal(uint32_t code, const char* namep, const VlRtmdSignalType& sigType,
                                 const VlRtmdDataType& dtype) {
    int msb;
    int lsb;
    const bool bussed = vlTraceRange(dtype, msb, lsb);
    const int bits = ((msb > lsb) ? (msb - lsb) : (lsb - msb)) + 1;

    std::string name_str = namep;
    if (bussed) name_str += " ["s + std::to_string(msb) + ":" + std::to_string(lsb) + "]";

    if (dtype.isEnum()) m_fst->emitEnumTableRef(m_local2fstdtype.at(dtype));

    using Direction = VlRtmdSignalType::Direction;
    fst::Hierarchy::VarDirection varDir = fst::Hierarchy::VarDirection::IMPLICIT;
    switch (sigType.direction()) {
    case Direction::INPUT:
    case Direction::CONSTREF: varDir = fst::Hierarchy::VarDirection::INPUT; break;
    case Direction::OUTPUT:
    case Direction::REF: varDir = fst::Hierarchy::VarDirection::OUTPUT; break;
    case Direction::INOUT: varDir = fst::Hierarchy::VarDirection::INOUT; break;
    case Direction::NONE: break;
    }

    // Nets by their kind, parameters, and variables by the type of their value
    using Kind = VlRtmdSignalType::Kind;
    using AtomKind = VlRtmdDataType::AtomKind;
    const AtomKind atomKind = vlFstAtomKind(dtype);
    bool isParam = false;
    fst::Hierarchy::VarType varType = fst::Hierarchy::VarType::SV_LOGIC;
    switch (sigType.kind()) {
    case Kind::GPARAM:
    case Kind::LPARAM:
    case Kind::SPECPARAM:
    case Kind::GENVAR:
        isParam = true;
        varType = fst::Hierarchy::VarType::VCD_PARAMETER;
        break;
    case Kind::WIRE:
    case Kind::WREAL: varType = fst::Hierarchy::VarType::VCD_WIRE; break;
    case Kind::TRI: varType = fst::Hierarchy::VarType::VCD_TRI; break;
    case Kind::TRI0: varType = fst::Hierarchy::VarType::VCD_TRI0; break;
    case Kind::TRI1: varType = fst::Hierarchy::VarType::VCD_TRI1; break;
    case Kind::TRIAND: varType = fst::Hierarchy::VarType::VCD_TRIAND; break;
    case Kind::TRIOR: varType = fst::Hierarchy::VarType::VCD_TRIOR; break;
    case Kind::SUPPLY0: varType = fst::Hierarchy::VarType::VCD_SUPPLY0; break;
    case Kind::SUPPLY1: varType = fst::Hierarchy::VarType::VCD_SUPPLY1; break;
    case Kind::VAR:
        switch (atomKind) {
        case AtomKind::INTEGER: varType = fst::Hierarchy::VarType::VCD_INTEGER; break;
        case AtomKind::BIT: varType = fst::Hierarchy::VarType::SV_BIT; break;
        case AtomKind::INT: varType = fst::Hierarchy::VarType::SV_INT; break;
        case AtomKind::SHORTINT: varType = fst::Hierarchy::VarType::SV_SHORTINT; break;
        // A chandle is traced as its 64 bit value
        case AtomKind::CHANDLE:
        case AtomKind::LONGINT: varType = fst::Hierarchy::VarType::SV_LONGINT; break;
        case AtomKind::BYTE: varType = fst::Hierarchy::VarType::SV_BYTE; break;
        case AtomKind::EVENT: varType = fst::Hierarchy::VarType::VCD_EVENT; break;
        case AtomKind::TIME: varType = fst::Hierarchy::VarType::VCD_TIME; break;
        case AtomKind::DOUBLE:
        case AtomKind::LOGIC: break;
        }
        break;
    }
    // Doubles have special decoding properties, so must indicate if a double
    if (atomKind == AtomKind::DOUBLE) {
        varType = isParam ? fst::Hierarchy::VarType::VCD_REAL_PARAMETER
                          : fst::Hierarchy::VarType::VCD_REAL;
    }

    // Room for the handle of this code, doubling the table if needed
    if (m_code2symbol.size() <= code) m_code2symbol.resize((code + 1) * 2, 0);
    vlFstHandle& handle = m_code2symbol[code];
    if (!handle) {  // New
        handle = m_fst->createVar(varType, varDir, bits, name_str.c_str(), 0);
    } else {  // Alias
        m_fst->createVar(varType, varDir, bits, name_str.c_str(), handle);
    }
}

//=============================================================================
// Get/commit trace buffer

VerilatedFst::Buffer* VerilatedFst::getTraceBuffer() { return new Buffer{*this}; }

void VerilatedFst::commitTraceBuffer(VerilatedFst::Buffer* bufp) { delete bufp; }

//=============================================================================
// VerilatedFstBuffer implementation

//=============================================================================
// Trace rendering primitives

// Note: emit* are only ever called from one place (full* in
// verilated_trace_imp.h, which is included in this file at the top),
// so always inline them.

VL_ATTR_ALWINLINE
void VerilatedFstBuffer::emitEvent(uint32_t code) {
    VL_DEBUG_IFDEF(assert(m_symbolp[code]););  // LCOV_EXCL_BR_LINE
    m_owner.emitTimeChangeMaybe();
    m_fst->emitValueChange(m_symbolp[code], 1);
}

VL_ATTR_ALWINLINE
void VerilatedFstBuffer::emitBit(uint32_t code, CData newval) {
    VL_DEBUG_IFDEF(assert(m_symbolp[code]););  // LCOV_EXCL_BR_LINE
    m_owner.emitTimeChangeMaybe();
    m_fst->emitValueChange(m_symbolp[code], uint64_t(newval));
}

VL_ATTR_ALWINLINE
void VerilatedFstBuffer::emitCData(uint32_t code, CData newval, int) {
    VL_DEBUG_IFDEF(assert(m_symbolp[code]););  // LCOV_EXCL_BR_LINE
    m_owner.emitTimeChangeMaybe();
    m_fst->emitValueChange(m_symbolp[code], newval);
}

VL_ATTR_ALWINLINE
void VerilatedFstBuffer::emitSData(uint32_t code, SData newval, int) {
    VL_DEBUG_IFDEF(assert(m_symbolp[code]););  // LCOV_EXCL_BR_LINE
    m_owner.emitTimeChangeMaybe();
    m_fst->emitValueChange(m_symbolp[code], newval);
}

VL_ATTR_ALWINLINE
void VerilatedFstBuffer::emitIData(uint32_t code, IData newval, int) {
    VL_DEBUG_IFDEF(assert(m_symbolp[code]););  // LCOV_EXCL_BR_LINE
    m_owner.emitTimeChangeMaybe();
    m_fst->emitValueChange(m_symbolp[code], newval);
}

VL_ATTR_ALWINLINE
void VerilatedFstBuffer::emitQData(uint32_t code, QData newval, int) {
    VL_DEBUG_IFDEF(assert(m_symbolp[code]););  // LCOV_EXCL_BR_LINE
    m_owner.emitTimeChangeMaybe();
    m_fst->emitValueChange(m_symbolp[code], newval);
}

VL_ATTR_ALWINLINE
void VerilatedFstBuffer::emitWData(uint32_t code, WDataInP newval, int) {
    VL_DEBUG_IFDEF(assert(m_symbolp[code]););  // LCOV_EXCL_BR_LINE
    m_owner.emitTimeChangeMaybe();
    m_fst->emitValueChange(m_symbolp[code], newval.datap());
}

VL_ATTR_ALWINLINE
void VerilatedFstBuffer::emitDouble(uint32_t code, double newval) {
    VL_DEBUG_IFDEF(assert(m_symbolp[code]););  // LCOV_EXCL_BR_LINE
    m_owner.emitTimeChangeMaybe();
    uint64_t newval_u64;
    std::memcpy(&newval_u64, &newval, sizeof(newval_u64));
    m_fst->emitValueChange(m_symbolp[code], newval_u64);
}
