---
# DESCRIPTION: Github actions config
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0
#
name: format
on:
  push:
    branches-ignore:
      - 'dependabot/**'  # Avoid duplicates: only run the PR, not the push

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-24.04
    name: Ubuntu 24.04 | format
    env:
      CI_RUNS_ON: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install packages for build
        run: |
          bash ci/ci-install.bash build &&
          sudo apt-get install clang-format-18 yapf3 &&
          sudo pip3 install gersemi mbake &&
          git config --global user.email "action@example.com" &&
          git config --global user.name "github action"
      - name: Format code
        run: |
          autoconf &&
          ./configure &&
          make -j 2 format CLANGFORMAT=clang-format-18 &&
          git status
      - name: Push
        run: |-
          if [ -n "$(git status --porcelain)" ]; then
            git commit . -m "Apply 'make format'" &&
            git push origin
          fi
